version: '3.8'
services:
  postgresql:
    image: postgres:15-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    volumes:
      - ./init.sh:/docker-entrypoint-initdb.d/init-db.sh:ro